-- ============================================================================
-- ReFound - initial schema
--
-- Conventions used throughout:
--   * Primary keys are UUIDs, generated by the database.
--   * Enum-like columns are text + CHECK, not native Postgres ENUM types.
--     Native enums cannot have values removed and are awkward to alter;
--     a CHECK gives the same safety and migrates trivially.
--   * Timestamps are timestamptz and stored in UTC.
--   * Every table has created_at. Mutable tables also have updated_at,
--     maintained by the trigger defined at the bottom of this file.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pg_trgm;    -- fuzzy text matching for the matcher


-- ============================================================================
-- app_user
--
-- "user" is a reserved word in Postgres, hence app_user.
-- One personal email, verified. matric_number and phone_number are unique so
-- one person cannot hold several accounts. phone_number is never public: it is
-- released only to the counterpart of an approved claim.
-- ============================================================================

CREATE TABLE app_user (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name       text        NOT NULL,
    matric_number   text        NOT NULL,
    email           text        NOT NULL,
    phone_number    text        NOT NULL,
    password_hash   text        NOT NULL,
    role            text        NOT NULL DEFAULT 'STUDENT',
    email_verified  boolean     NOT NULL DEFAULT false,
    status          text        NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT app_user_role_valid   CHECK (role   IN ('STUDENT', 'ADMIN')),
    CONSTRAINT app_user_status_valid CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

-- Emails and matric numbers are compared case-insensitively. Storing the raw
-- value but indexing the lowered form keeps display intact while making
-- "Alex@x.com" and "alex@x.com" the same account.
CREATE UNIQUE INDEX ux_app_user_email  ON app_user (lower(email));
CREATE UNIQUE INDEX ux_app_user_matric ON app_user (lower(matric_number));
CREATE UNIQUE INDEX ux_app_user_phone  ON app_user (phone_number);


-- ============================================================================
-- verification_token - email verification and password reset
--
-- Only the hash of the token is stored. A leaked database must not hand out
-- working reset links.
-- ============================================================================

CREATE TABLE verification_token (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash  text        NOT NULL UNIQUE,
    purpose     text        NOT NULL,
    expires_at  timestamptz NOT NULL,
    used_at     timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT verification_token_purpose_valid
        CHECK (purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET'))
);

CREATE INDEX ix_verification_token_user ON verification_token (user_id);


-- ============================================================================
-- refresh_token
--
-- Rotated on every use: the old row is revoked and a new one issued.
-- ============================================================================

CREATE TABLE refresh_token (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash  text        NOT NULL UNIQUE,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_refresh_token_user ON refresh_token (user_id);


-- ============================================================================
-- item - both lost reports and found reports
--
-- One table, discriminated by `type`. They share every field except
-- verification_answer, and matching a LOST against a FOUND is a single
-- self-join rather than a cross-table query.
--
-- Location comes from a map pin, not a fixed list of places:
--   latitude/longitude  the dropped pin
--   location_label      optional name, typed or reverse-geocoded
--   location_detail     free text, e.g. "second floor, near the stairs"
--
-- verification_answer is the private detail only the true owner would know.
-- It is FOUND-only, mandatory there, and must never appear in any DTO served
-- to a student. Admins see it during claim review.
-- ============================================================================

CREATE TABLE item (
    id                   uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    type                 text          NOT NULL,
    status               text          NOT NULL DEFAULT 'OPEN',
    reporter_id          uuid          NOT NULL REFERENCES app_user (id),
    category             text          NOT NULL,
    title                text          NOT NULL,
    description          text,
    latitude             numeric(9,6),
    longitude            numeric(9,6),
    location_label       text,
    location_detail      text,
    occurred_on          date          NOT NULL,
    attributes           jsonb         NOT NULL DEFAULT '{}'::jsonb,
    verification_answer  text,
    photos_public        boolean       NOT NULL DEFAULT true,
    hidden               boolean       NOT NULL DEFAULT false,
    expires_at           timestamptz   NOT NULL,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT item_type_valid CHECK (type IN ('LOST', 'FOUND')),

    CONSTRAINT item_status_valid CHECK (status IN (
        'OPEN', 'CLAIM_PENDING', 'MATCHED', 'RETURNED', 'EXPIRED', 'CANCELLED')),

    CONSTRAINT item_category_valid CHECK (category IN (
        'PHONE', 'LAPTOP', 'ID_CARD', 'KEYS', 'BAG', 'BOOK',
        'WALLET', 'CLOTHING', 'JEWELLERY', 'OTHER')),

    -- A found item must carry a verification answer; a lost item must not.
    CONSTRAINT item_verification_answer_matches_type CHECK (
        (type = 'FOUND' AND verification_answer IS NOT NULL)
     OR (type = 'LOST'  AND verification_answer IS NULL)
    ),

    -- Coordinates travel as a pair or not at all.
    CONSTRAINT item_coordinates_paired CHECK (
        (latitude IS NULL) = (longitude IS NULL)
    ),

    CONSTRAINT item_latitude_range  CHECK (latitude  IS NULL OR latitude  BETWEEN  -90 AND  90),
    CONSTRAINT item_longitude_range CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

-- Browse: filter by type + status + category, newest first.
CREATE INDEX ix_item_browse ON item (type, status, category, created_at DESC);

CREATE INDEX ix_item_reporter    ON item (reporter_id);
CREATE INDEX ix_item_occurred_on ON item (occurred_on);

-- Expiry sweep only ever looks at open items.
CREATE INDEX ix_item_expiry ON item (expires_at) WHERE status = 'OPEN';

-- Proximity scoring and map bounding-box queries.
CREATE INDEX ix_item_coordinates ON item (latitude, longitude)
    WHERE latitude IS NOT NULL;

-- Fuzzy text search. GIN + gin_trgm_ops is what makes similarity() fast;
-- without these the matcher degrades to a sequential scan.
CREATE INDEX ix_item_title_trgm       ON item USING gin (title       gin_trgm_ops);
CREATE INDEX ix_item_description_trgm ON item USING gin (description gin_trgm_ops);

-- Category-specific fields: colour, brand, model, serial.
CREATE INDEX ix_item_attributes ON item USING gin (attributes);


-- ============================================================================
-- item_photo
-- ============================================================================

CREATE TABLE item_photo (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id     uuid        NOT NULL REFERENCES item (id) ON DELETE CASCADE,
    url         text        NOT NULL,
    position    integer     NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT item_photo_position_valid CHECK (position >= 0 AND position < 5)
);

CREATE INDEX ix_item_photo_item ON item_photo (item_id, position);


-- ============================================================================
-- claim
--
-- A claim is one person asserting ownership of one found item.
-- Several people may claim the same item; an admin approves at most one.
--
-- lost_item_id links the claimant's own lost report when they filed one.
-- It is nullable: plenty of people never report the loss and only discover
-- the item while browsing.
-- ============================================================================

CREATE TABLE claim (
    id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    found_item_id         uuid        NOT NULL REFERENCES item (id) ON DELETE CASCADE,
    lost_item_id          uuid        REFERENCES item (id) ON DELETE SET NULL,
    claimant_id           uuid        NOT NULL REFERENCES app_user (id),
    description           text        NOT NULL,
    lost_context          text,
    status                text        NOT NULL DEFAULT 'PENDING',
    info_request          text,
    reviewed_by           uuid        REFERENCES app_user (id),
    decision_reason       text,
    decided_at            timestamptz,
    finder_confirmed_at   timestamptz,
    claimant_confirmed_at timestamptz,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT claim_status_valid CHECK (status IN (
        'PENDING', 'AWAITING_INFO', 'APPROVED', 'REJECTED', 'WITHDRAWN')),

    -- A decision must record who made it, when, and why. This is the audit
    -- guarantee the verification workflow rests on.
    CONSTRAINT claim_decision_complete CHECK (
        status NOT IN ('APPROVED', 'REJECTED')
        OR (reviewed_by IS NOT NULL
            AND decided_at IS NOT NULL
            AND decision_reason IS NOT NULL)
    )
);

-- One live claim per person per item. Rejected or withdrawn claims are
-- excluded, so a rejected claimant may appeal with a better description.
CREATE UNIQUE INDEX ux_claim_one_active_per_claimant
    ON claim (found_item_id, claimant_id)
    WHERE status IN ('PENDING', 'AWAITING_INFO');

CREATE INDEX ix_claim_found_item ON claim (found_item_id, status);
CREATE INDEX ix_claim_claimant   ON claim (claimant_id);

-- The admin review queue: oldest pending first.
CREATE INDEX ix_claim_queue ON claim (status, created_at)
    WHERE status IN ('PENDING', 'AWAITING_INFO');


-- ============================================================================
-- claim_evidence - receipts, older photos, IMEI screenshots
--
-- Private. Served through a signed, expiring URL, never publicly.
-- ============================================================================

CREATE TABLE claim_evidence (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    claim_id    uuid        NOT NULL REFERENCES claim (id) ON DELETE CASCADE,
    url         text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_claim_evidence_claim ON claim_evidence (claim_id);


-- ============================================================================
-- item_match - candidate pairs produced by the matching engine
--
-- breakdown stores each signal's contribution, so any suggestion can be
-- explained afterwards and the weights tuned against real data.
-- ============================================================================

CREATE TABLE item_match (
    id             uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
    lost_item_id   uuid          NOT NULL REFERENCES item (id) ON DELETE CASCADE,
    found_item_id  uuid          NOT NULL REFERENCES item (id) ON DELETE CASCADE,
    score          numeric(4,3)  NOT NULL,
    breakdown      jsonb         NOT NULL DEFAULT '{}'::jsonb,
    status         text          NOT NULL DEFAULT 'SUGGESTED',
    created_at     timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT item_match_score_range  CHECK (score BETWEEN 0 AND 1),
    CONSTRAINT item_match_status_valid CHECK (status IN ('SUGGESTED', 'DISMISSED', 'CLAIMED')),
    CONSTRAINT item_match_distinct     CHECK (lost_item_id <> found_item_id)
);

-- The same pair is scored once; a rescore updates the row.
CREATE UNIQUE INDEX ux_item_match_pair ON item_match (lost_item_id, found_item_id);

-- "Best candidates for my lost item", which is how the UI reads it.
CREATE INDEX ix_item_match_lost  ON item_match (lost_item_id,  score DESC);
CREATE INDEX ix_item_match_found ON item_match (found_item_id, score DESC);


-- ============================================================================
-- audit_event - append-only
--
-- Never updated, never deleted. actor_id is nullable because the system
-- itself acts (expiry sweeps, automatic matching). ON DELETE SET NULL keeps
-- the record intact if an account is ever removed: the event still happened.
-- ============================================================================

CREATE TABLE audit_event (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id     uuid        REFERENCES app_user (id) ON DELETE SET NULL,
    entity_type  text        NOT NULL,
    entity_id    uuid        NOT NULL,
    action       text        NOT NULL,
    metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_audit_event_entity ON audit_event (entity_type, entity_id, created_at DESC);
CREATE INDEX ix_audit_event_actor  ON audit_event (actor_id, created_at DESC);
CREATE INDEX ix_audit_event_time   ON audit_event (created_at DESC);


-- ============================================================================
-- notification
--
-- Persisted first, dispatched asynchronously. A failed SMTP call must never
-- fail the request that triggered it.
-- ============================================================================

CREATE TABLE notification (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid        NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    type        text        NOT NULL,
    payload     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    channel     text        NOT NULL DEFAULT 'IN_APP',
    sent_at     timestamptz,
    read_at     timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT notification_channel_valid CHECK (channel IN ('EMAIL', 'IN_APP')),

    CONSTRAINT notification_type_valid CHECK (type IN (
        'EMAIL_VERIFICATION',
        'PASSWORD_RESET',
        'MATCH_FOUND',
        'CLAIM_SUBMITTED',
        'CLAIM_INFO_REQUESTED',
        'CLAIM_APPROVED',
        'CLAIM_REJECTED',
        'HANDOVER_REMINDER',
        'ITEM_EXPIRING'))
);

CREATE INDEX ix_notification_user ON notification (user_id, created_at DESC);

-- Unread badge count.
CREATE INDEX ix_notification_unread ON notification (user_id) WHERE read_at IS NULL;

-- Outbox: what still needs sending.
CREATE INDEX ix_notification_pending ON notification (created_at) WHERE sent_at IS NULL;


-- ============================================================================
-- updated_at maintenance
--
-- Handled by the database rather than by application code, so a row touched
-- by a migration or a manual fix still gets a correct timestamp.
-- ============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_app_user_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_item_updated_at
    BEFORE UPDATE ON item
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_claim_updated_at
    BEFORE UPDATE ON claim
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
